name: CI & Version Bump (if needed)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
        torch-version: ["2.6.0", "2.7.0"]
    name: Python ${{ matrix.python-version }} / Torch ${{ matrix.torch-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install project with selected PyTorch
        run: |
          pip install --upgrade pip
          pip install torch~=${{ matrix.torch-version }}
          pip install .

      - name: Run tests
        run: pytest

  bump-version:
    needs: tests
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Commitizen
        run: pip install commitizen

      - name: Configure Git user
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Bump version and create tag (if needed)
        continue-on-error: true
        run: |
          cz bump --yes --tag-format v$version || echo "No version bump needed."

      - name: Push changes and tag
        if: success()  # runs only if the bump step did update the version
        run: |
          git push origin HEAD:main
          git push --tags